name: Find Open API Specs, update them, and analyze them for vulnerabilities

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  scan-and-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Step 1: Scan for OpenAPI Specification files
      - name: Scan for OpenAPI files
        id: scan
        run: |
          FILES=$(find . -name '*.yaml' -o -name '*.json' | xargs grep -l "openapi" || true)
          echo "Found OpenAPI files: $FILES"
          echo "OPENAPI_FILES=$FILES" >> $GITHUB_ENV

      # Step 2: Run spec update and lint jobs on found OpenAPI files
      - name: Run Spec Update and Lint
        if: env.OPENAPI_FILES != ''
        run: |
          for FILE in $OPENAPI_FILES; do
            echo "Processing $FILE"
            npx @impart-security/impart-cli specs update --specPath $FILE --force
            npx @impart-security/impart-cli specs lint --specPath $FILE --failSeverity warn --format pretty
          done
        env:
          IMPART_ACCESS_TOKEN: ${{ secrets.SPEC_UPDATE_TOKEN }}
